build-module-release:
  variables:
    http_proxy: $CODE_PROXY
    https_proxy: $CODE_PROXY
    no_proxy: code.siemens.com,$CI_REGISTRY
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $CI_COMMIT_TAG
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor 
      --context $CI_PROJECT_DIR 
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile.module 
      --build-arg http_proxy=$CODE_PROXY 
      --build-arg https_proxy=$CODE_PROXY 
      --build-arg no_proxy=code.siemens.com,$CI_REGISTRY 
      --destination $CI_REGISTRY/openswarm/energy-community-controller-bifrost-connector:$CI_COMMIT_TAG 
      --destination $CI_REGISTRY/openswarm/energy-community-controller-bifrost-connector:latest
  tags:
    - DOCKER
  rules:
    - if: $CI_COMMIT_REF_NAME =~ "/^v\d+(.\d+){2}$/"
