FROM node:18.16.1-slim

WORKDIR /opt/bifrost/moduletemplate/

# set up node environment
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install

# copy module files
COPY src/ ./src/
COPY data/ ./data/

RUN npm run tsc

CMD ["npm", "run", "module"]