name: devsetup
services:
    mqtt-broker: 
        image: emqx/emqx
        ports:
            - 1883:1883
 
    influxdb:
        image: influxdb:2.7.5-alpine
        environment:
            DOCKER_INFLUXDB_INIT_MODE: 'setup'
            DOCKER_INFLUXDB_INIT_USERNAME: 'admin'
            DOCKER_INFLUXDB_INIT_PASSWORD: '~*@Zq?>vUQa_3RyW'
            DOCKER_INFLUXDB_INIT_ORG: 'siemens'
            DOCKER_INFLUXDB_INIT_BUCKET: 'siemens'
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: '1d478854045f485ac83e0c39a04c0edae20ea94295c222850f1b64dfd1161b65'
  
    bifrost-core:
        image: cr.siemens.com/bifrost/bifrost-zero:rc-v1.4
        environment:
            BIFROST__cdl_url: '"http://influxdb:8086"'
            BIFROST__cdl_startupAttempts: 20
            BIFROST__server_host: '"::"'
            BIFROST__simulation_replayDurationTarget: 5
            BIFROST__simulation_replaySpeedMap_SLOW: 6
            BIFROST__simulation_replaySpeedMap_NORMAL: 3
            BIFROST__simulation_replaySpeedMap_FAST: 1
        depends_on:
            - influxdb  
        ports:
            - 9091:9091

    fenrir:
        image: cr.siemens.com/bifrost/bifrost-fenrir:zero-v1.4.0
        environment:
            MODULE_URL: "http://fenrir:7001"
            BIFROST_URL: "http://bifrost-core:9091"
            SAMPLING_RATE: 900
        depends_on:
            - bifrost-core

    energy-community-asset-simulator:
        image: cr.siemens.com/openswarm/energy-community-asset-simulator:v1.1.0
        environment:
            BIFROST_URL: 'http://bifrost-core:9091'
            MODULE_URL: 'http://energy-community-asset-simulator:1809'
            SAMPLING_RATE: 900