name: energy-community
services:
    mqtt-broker: 
        image: emqx/emqx
        ports:
            - 1883:1883

    influxdb:
        image: influxdb:2.7.5-alpine
        environment:
            DOCKER_INFLUXDB_INIT_MODE: 'setup'
            DOCKER_INFLUXDB_INIT_USERNAME: 'openswarm_user'
            DOCKER_INFLUXDB_INIT_PASSWORD: 'openswarm_str0ng_passw0rd'
            DOCKER_INFLUXDB_INIT_ORG: 'openswarm'
            DOCKER_INFLUXDB_INIT_BUCKET: 'openswarm'
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 'C8TXsDAjcGfCKqZJY6fI+u268gUMdRWhj6MpbZexj38='

    bifrost-core:
        image: cr.siemens.com/bifrost/bifrost-zero:rc-v1.4
        environment:
            BIFROST__server_host: '"::"'
            BIFROST__cdl_url: '"http://influxdb:8086"'
            BIFROST__cdl_org: '"openswarm"'
            BIFROST__cdl_user: '"openswarm_user"'
            BIFROST__cdl_token: '"C8TXsDAjcGfCKqZJY6fI+u268gUMdRWhj6MpbZexj38="'
        depends_on:
            - influxdb  
        ports:
            - 9091:9091

    fenrir:
        image: cr.siemens.com/bifrost/bifrost-fenrir:zero-v2.0.0
        environment:
            MODULE_URL: 'http://fenrir:7001'
            BIFROST_URL: 'http://bifrost-core:9091'
            SAMPLING_RATE: 60
            HOOK: '[110]'
        depends_on:
            - bifrost-core

    energy-community-asset-simulator:
        image: cr.siemens.com/openswarm/energy-community-asset-simulator:v2.1.0
        environment:
            BIFROST_URL: 'http://bifrost-core:9091'
            MODULE_URL: 'http://energy-community-asset-simulator:1809'
            SAMPLING_RATE: 60
            HOOK: '[100, 200]'
            NODE_ENV: 'production'

    energy-community-controller-connector:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.module
        image: energy-community-controller-connector:latest
        environment:
            BIFROST_URL: 'http://bifrost-core:9091'
            MODULE_URL: 'http://energy-community-controller-connector:1809'
            MQTT_URL: 'mqtt://mqtt-broker'
            SAMPLING_RATE: 60
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - bifrost-core
            - mqtt-broker